name: hw3_task2_lerobot
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pillow
  - imageio
  - requests
  - pyyaml
  - tqdm
  - scikit-learn
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip:
      - "huggingface_hub[hf_xet]"
      - datasets
      - safetensors
      - wandb
      - swanlab
      - opencv-python
      - pybullet
      - pytest
      - "sentence-transformers==3.4.1"
      - "lerobot==0.5.1"
